```{r}


  library(package = "stringr")
  library(package = "forcats")
  library(package = "readr")
  library(package = "tidyverse")
  library(package = "lubridate")
  library(package = "RCurl")


```

```{r}

thredds_root= "http://kyrill.ias.sdsmt.edu:8080/thredds/fileServer/LOCA_NGP/Specific_Regional_Aggregate_Sets/huc_08_basins/R_Daily_Files/"


get_metadata = "http://kyrill.ias.sdsmt.edu:8080/thredds/fileServer/LOCA_NGP/Specific_Regional_Aggregate_Sets/huc_08_basins/HUC08_Missouri_River_Basin.Rdata"

load(url(get_metadata), verbose=TRUE)



hucs_to_process = c("10120202")

HUC08_MRB_LUT = HUC08_MRB_LUT %>% filter(HUC08_Code_ID %in% hucs_to_process)



```

```{r}


  Output_Scenarios = c("RCP 4.5",
                       "RCP 8.5")

  for (basin in hucs_to_process)
  {

    metadata = HUC08_MRB_LUT %>% filter(HUC08_Code_ID == basin)
    
    spatial = HUC08_MRB_Code_Frame %>% 
      filter(HUC08_Code_ID == basin) %>% 
      group_by(HUC08_Code_ID) %>% 
      summarize(lat = mean(lat),
                lon = mean(lon))


    File_URL = str_c(thredds_root,
                     "NGP_LOCA_HUC08_",
                     basin,
                     ".RData",
                     sep = "")

    my.connection = url(description = File_URL)
      load(file = my.connection)
      close(con = my.connection)
      remove( my.connection)

    ensembles =  unique(loca_daily$Ensemble)
    print(ensembles)
    print(length(ensembles))
    for (ensemble in unique(loca_daily$Ensemble))
    {

      for (scenario in Output_Scenarios)
      {

        subset = loca_daily %>%
                       filter(((Scenario  == "Historical") |
                               (Scenario  == scenario)) &
                              (Ensemble   == ensemble) &
                              (Percentile == "MEAN")) %>%
                       mutate(Year   = year(Time),
                              Julian = yday(Time))

        #
        # Write the Daily Max/Min Temperature File
        #
        
        subset$TSTEP = seq(1,nrow(subset))


        filename_tmp = str_c("./SWAT_LOCA_",
                             basin,
                             "__",
                             ensemble,
                             "__",
                             str_replace(string      = scenario,
                                         pattern     = " ",
                                         replacement = ""),
                             ".TMP",
                             sep = "")
        
                filename_tmp = str_replace(string      = filename_tmp,
                                   pattern     = ".5",
                                   replacement = "5")

        line_1 = str_c("my_temps.tmp: ", filename_tmp)
        line_2 = "NBYR     TSTEP        LAT          LON          ELEV"
        line_3 = "150          0   44.40000   -103.47000    1005.79999"
                      

        fileConn<-file(filename_tmp)
          writeLines(c(line_1,line_2,line_3), fileConn)
          close(fileConn)
          
          subperiod_print = subset %>%
            select("Year","TSTEP","tasmax","tasmin")

          
          write_delim(x     = subperiod_print, 
                      file  =  filename_tmp, 
                      delim =       " ",
                      append=TRUE) 
     





        #
        # Write the Daily Rainfall File
        #        

        filename_pcp = str_c("./SWAT_LOCA_",
                             basin,
                             "__",
                             ensemble,
                             "__",
                             str_replace(string      = scenario,
                                         pattern     = " ",
                                         replacement = ""),
                             ".PCP",
                             sep = "")
        filename_pcp = str_replace(string      = filename_pcp,
                                   pattern     = ".5",
                                   replacement = "5")

         line_1 = str_c("my_precip.pcp: ", filename_pcp)
        line_2 = "NBYR     TSTEP        LAT          LON          ELEV"
        line_3 = "150          0   44.40000   -103.47000    1005.79999"
                      

        fileConn<-file(filename_pcp)
          writeLines(c(line_1,line_2,line_3), fileConn)
          close(fileConn)
          
          subperiod_print = subset %>%
            select("Year","TSTEP","pr")

          
          write_delim(x     = subperiod_print, 
                      file  =  filename_pcp, 
                      delim =       " ",
                      append=TRUE) 



        #
        # Clean Up
        #

        remove(subset)
        remove(filename_tmp)
        remove(filename_pcp)
      } # scenario

    } # ensemble

  } # basin
  remove(ensemble)
  remove(scenario)
  remove(basin)



```
